### ISSUE TITLE
HELP??!?!!

### ISSUE THREAD

**Issue by Snizzzle** [rwf93/SonsOfTheForestCheatConsole#2]
MY PC BLEW THE FUCK UP??!!?!?!???!!?
:(

**Comment by rwf93** [comment]
:(

**Comment by 2048khz-gachi-rmx** [comment]
EXCEPTION!!! PRIVATE, THROW IT BACK

Private named C#:
![private](https://user-images.githubusercontent.com/44749188/221407172-4d5c61f8-7b20-460c-8f4c-a5afb9314786.png)

**Comment by Xeth6470** [comment]
SIR YES SIR OOHRAH!!!!!

**Comment by rwf93** [comment]
this code might help the problem at hand.

```
try {
  throw new System.Exception("QUICK PRIVATE, THROW IT BACK");
 } catch {
   // the private in question
   ThrowingItBack();
}
```

**Comment by Xeth6470** [comment]
> this code might help the problem at hand.
> 
> ```
> try {
>   throw new System.Exception("QUICK PRIVATE, THROW IT BACK");
>  } catch {
>    // the private in question
>    ThrowingItBack();
> }
> ```

Had the same issue this solved it much thanks! cheers😁😁😁

**Comment by Snizzzle** [comment]
> this code might help the problem at hand.
> 
> ```
> try {
>   throw new System.Exception("QUICK PRIVATE, THROW IT BACK");
>  } catch {
>    // the private in question
>    ThrowingItBack();
> }
> ```

You're a lifesaver, this solved the issue right away!
